version: "3.8"

services:
    postgres:
        image: postgres:16
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: growthos
            POSTGRES_PASSWORD: 123456789
            POSTGRES_DB: growthos
            TZ: Asia/Kolkata
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7
        container_name: redis
        restart: always
        command: ["redis-server", "--requirepass", "123456789"]
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    inngest:
        image: inngest/inngest:latest
        container_name: inngest

        ports:
            - "8288:8288"

        environment:
            INNGEST_DEV: "1"
            INNGEST_PORT: "8288"
            INNGEST_EVENT_KEY: 91f3fbc0b3c7d18b0d77e57fd82d5f6a8f1d2f4a89c7b3d6

        command: >
            inngest dev
            -u http://host.docker.internal:3100/api/inngest

        restart: unless-stopped
volumes:
    postgres_data:
    redis_data:
